name: .NET Build

on:
  push:
    branches:
      - main  # Triggers the build when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Triggers the build on pull requests targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: 'Checkout source code'
        uses: actions/checkout@v3

      # Step 2: Set up .NET SDK
      - name: 'Set up .NET Core SDK'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'  # Use the .NET version you're targeting

      # Step 3: Restore dependencies
      - name: 'Restore dependencies'
        run: dotnet restore

      # Step 4: Build the project
      - name: 'Build the project'
        run: dotnet build --configuration Release --no-restore

      # Step 5: (Optional) Run tests
      - name: 'Run unit tests'
        run: dotnet test --no-build --verbosity normal
